### ISSUE TITLE
Error trying to download stream on CB

### ISSUE THREAD

**Issue by ParadingLunatic** [PurrSevere/streamdvr-docker#7]
I just recently moved this to a brand new docker instance on a new system.  Prior to moving I did see this every so often but not constant.  On this new system I'm seeing this error constantly and nothing is being grabbed.  I only grab CB at the moment so I can't really test any other stream.

[20191007_142723] CB       [ERROR] ERROR: Unable to download webpage: <urlopen error [Errno -3] Try again> (caused by URLError(gaierror(-3, 'Try again'),))

edit....
Ok so I pulled the regular "latest" tag  instead of the "xxx" tag, then just pointed it to the same config folder (removed the mfc.yml) and it works fine.  Not sure what's different with the xxx tag image.

**Comment by PurrSevere** [comment]
This error can come up due to network problems or if you have a very low refresh interval.

The difference between the tags is that the `xxx` tag mainly adds MFC (Currently not working) support by including the mfc.js plugin and its dependencies. 

CB might be working for you with the `latest` tag because you probably have the cb.yml and cb_updates.yml files in the config directory. That's all that is needed to make CB work in the `latest` tag.

**Comment by ParadingLunatic** [comment]
Thought I'd provide an update.  As of the most recent image update, now it appears to be failing constantly with the same error.  I was randomly getting that error before but it would still download streams.  Now it won't download at all and always gets that same error.  It's definitely not my network as I have no problem with anything else.  For a while I thought it could be DNS (I'm running a network wide ad-blocker which uses DNS) so I passed extra commands to use public DNS servers and that didn't fix it either.  I know the error is directly associated with the youtube-dl component and from looking it up, others say it's a name resolution issue.  No clue why I'm having these issues when I'm not having any name resolution issues anywhere else on my network.

**Comment by PurrSevere** [comment]
By any chance are you running this behind a proxy or VPN?

I have tested the latest build on a few fresh installs and I can't replicate your issue.

**Comment by ParadingLunatic** [comment]
Nope I have it running on my NAS (openmediavault which is debian based) with the network configured in host mode instead of bridged.  I'll see if I can try it on another docker instance to see if it makes any difference.

**Comment by ParadingLunatic** [comment]
Just tried it on a Linuxmint VM I have (both systems are VM's on an ESXi host) and it's working there.  I copied the config folder from my NAS to the Linux Mint VM, set up the volumes, fired it up and no problems at all.  Wonder what the issue is running it on my NAS.  They're both VM's on the same ESXi host, both on the same network, same DNS servers, etc.  I'll keep working on trying to figure out the issue on the NAS since that's obviously where I want to store the files.  If I can't get it working, I'll just do an NFS mount and do it that way.

**Comment by PurrSevere** [comment]
You can execute `docker exec -it streamdvr bash`.
That'll get you inside the container.

**Comment by ParadingLunatic** [comment]
Yeah I finally had a chance and took a look.  No clue what the problem is on that specific system.  I didn't see any DNS resolution issues, I was able to ping by domain name, it resolved and replied.  I didn't try doing a wget (as I'm guessing the container probable doesn't have it).  Not sure what else I can really do to try and resolve it.  Being that this doesn't appear to be an issue with the docker image I'm just going to go ahead and close it.

**Comment by ParadingLunatic** [comment]
After quite a bit of messing around....I think I've narrowed down the issue, at least on the one system.  

It looks like everything in the container is run under UID/GID of 1000.  When I console in using that UID/GID, I can't access ANYTHING network related.  Name resolution fails, can't ping, etc.  When I console in as root, I have no problems accessing the network, name resolution and ping work fine.

Honestly I don't have the slightest idea where to begin to resolve this so I can finally move this back to my primary system I use docker on.

**Comment by ParadingLunatic** [comment]
For now I've created my own image using most of the dockerfile info you have in yours, except I removed

RUN chown 1000:1000 -R /app

USER node

So far it appears to be working.  I have no clue why this suddenly became an issue, and only seems to be an issue on my NAS (Openmediavault 4)
